Repository Caleydo/tdp_gene, pull requests merged in 2019-12, with the labels that each got.

#105 Update template files and dependencies
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  buildInfo.js
  index.js
  package-lock.json
  package.json
  webpack.config.js
Labels: release: major, type: technical debt

#107 Set jQuery object to `any` to fix sortable typing
  src/views/AOncoPrint.ts
Labels: release: patch, type: bug

#110 Add TS compiler flags for i18n to tsconfig.json
  tsconfig.json
Labels: release: minor

#109 Remove optional dependency for dTiles
  package.json
  src/SearchProvider.ts
Labels: type: refactor
